# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.SlugField(max_length=30),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.SlugField(max_length=30),
        ),
    ]
