# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170501_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='channel',
            name='slug',
            field=models.SlugField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
